version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "created python 3.11 runtime...."
      - pwd
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Currently in build phase....."
      - echo "Zipping deployment package....."
      - cd lib
      - zip -r9 ../airbnb_deployment_package.zip .
      - cd ..
      - zip -g airbnb_deployment_package.zip lambda_function.py
  post_build:
    commands:
      - echo " Uploading to s3...."
      - aws s3 cp airbnb_deployment_package.zip s3://cicd-east2-packages/
      - echo "Updating Lambda function via s3...."
      - aws lambda update-function-code --function-name ProducerAirbnbBookingData --s3-bucket cicd-packages --s3-key airbnb_deployment_package.zip
      - echo "Deployment complete!..."